docs/mixin.md
=> Mixin injection failed example

docs/.vitepress/config.ts, docs/team.md
为截至本 Pull request 提交前所有在 [GlobeMC/crashmc.com](https://github.com/GlobeMC/crashmc.com/graphs/contributors) 贡献者名单上的成员（包含 README.md 上的成员）添加进 team.md
文档贡献者按 A to Z 进行排序。
=> 补充 team.md 成员列表

.github/reviewer-lottery.yml, docs/clients.md
=> ✨ update: client docs and CI

docs/clients.md
- 更新clients.md: .DS_Store 文件夹 -> .DS_Store 文件
=> 更新clients.md: .DS_Store 文件夹 -> .DS_Store 文件

docs/clients.md
=> add: 添加了 Fabric Mod 冲突的解决方案

docs/clients.md
=> ✨ update: 更改存档损坏的解决方案

docs/index.md
=> ✨ update: 更新主页文案

docs/client/system.md
=> 添加imblocker不支持linux

docs/client/mods.md
=> 增加neoforge缺少前置

docs/server/mods.md
行号以修改后为准。
行 5-16：参考自 [Fabric 1.20.1 Server Log](https://mclo.gs/CDHsmDt)。
行 23：举例应放在一起，一前一后容易引人误解。
行 26-33：统一格式。
=> ✨ update: 更新 Mod 服务端文档

README.md, docs/client/vanilla.md
解决方法参考了 [MC-34749](https://bugs.mojang.com/browse/MC-34749) 中 Mojang 官方及评论区 June Hanabi 提及的解决方案。
写的时候有点急（）有点问题请多包涵~
=> 添加由防火墙或防病毒软件引起的崩溃问题

docs/.vitepress/theme/components/ReloadPrompt.vue
=> add animation for the pwa refresh prompt

docs/.vitepress/cdn.js, docs/.vitepress/scripts/pwa.ts, docs/.vitepress/theme/components/Analyzer.vue, docs/.vitepress/theme/components/Contributors.vue, package.json, pnpm-lock.yaml
- use MCLA web assembly module as the first analyzer
- fixed styles
- use vue-router instead of window.href
=> 更新Analyzer, 使用MCLA API并修复一些错误

docs/client/mods.md
参考自：[错误报告-2023-9-2_11.56.06.zip](https://github.com/GlobeMC/crashmc.com/files/12504109/-2023-9-2_11.56.06.zip)
=> 添加 Forge 其它崩溃原因

docs/.vitepress/analyzers/mcla.ts, docs/.vitepress/cdn.ts, docs/.vitepress/theme/components/Analyzer.vue, docs/.vitepress/theme/components/index.d.ts, docs/src/mcla_worker.js, package.json, pnpm-lock.yaml, tsconfig.json
- use web worker when possible to prevent stuck the browser
- add command docs:tsc for typescript check
- bump MCLA to v0.4.14
=> 支持Web worker, 使用多线程分析保证浏览器渲染流畅

docs/.vitepress/analyzers/mcla.ts, docs/src/mcla_worker.js
现在将会提前缓存数据库，不会出现第一次分析时几千个请求的情况了。。。
=> Bump MCLA to v0.4.18

.github/ISSUE_TEMPLATE/CRASH-UPLOAD.yml
Reverts GlobeMC/crashmc.com#175
没有按预期工作
=> Revert "Update CRASH-UPLOAD.yml"

docs/server/plugins.md, docs/server/vanilla.md
针对原版问题，建议用户前往到通用问题下寻求帮助
事实上，我觉得可以把原版问题都建议用户尝试在通用问题中寻求帮助（因为通用问题本身就意味着会在任何版本中出现）
=> 更新了服务器分类下的插件和原版问题

docs/.vitepress/config.ts, docs/.vitepress/theme/components/Analyzer.vue, docs/.vitepress/theme/components/TransitionExpand.vue, docs/.vitepress/theme/components/TransitionExpandGroup.vue
- fix expand transition
- fix a format issue
修复了垂直展开的动画
=> Fix expand transition

docs/.vitepress/analyzers/mcla.ts
- bump MCLA to v0.5.1 Fix line number
=> bump MCLA to v0.5.1
